idf_component_register(
    SRCS
        "main.c"
    REQUIRES
        bsp
        input
        shell
        registry
        net
        nvs_flash
        esp_lcd
    EMBED_TXTFILES
        "builtin/hello.manifest.json"
        "builtin/hello.ui.jsonl"
        "builtin/weather.manifest.json"
        "builtin/weather.ui.jsonl"
        "builtin/clock.manifest.json"
        "builtin/clock.ui.jsonl"
)
