idf_component_register(
    SRCS
        "widget.c"
        "datasource.c"
        "datasource_http.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        registry
        net
        host
        json
        esp_http_client
        esp-tls
        lvgl__lvgl
        espressif__esp_lvgl_port
        nvs_flash
)
