idf_component_register(
    SRCS
        "shell.c"
        "settings.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        bsp
        json
        input
        registry
        widget
        catalog
        net
        host
        ota
        fetch
        webcfg
        esp_lcd
        nvs_flash
        esp_app_format
        esp_system
)
